#!/bin/bash
cd "$(dirname "$0")"
sudo -S chown -R root:wheel ./*.kext
sudo chown -R root:wheel ./*.kext
sudo chmod -R 755 *.kext
sudo kextload -v VoodooI2C.kext
sudo kextload -v VoodooI2CHID.kext
exit
